name: Update Emails

on:
  push:
    branches:
      - main

jobs:
  update-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install faker pyyaml

      - name: Generate Emails
        run: |
          python script.py

      - name: Create Folders and Move Files
        run: |
          bases=("bharathbansal@gmail.com" "bharathbansal@outlook.com" "bharathbansal@yahoo.com" "bharathbansal@hotmail.com" "bharathbansal@aol.com" "bharathbansal@icloud.com" "bharathbansal@proton.me" "bharathbansal@gmx.com")
          for base in "${bases[@]}"; do
            domain=$(echo $base | cut -d '@' -f 2 | cut -d '.' -f 1)
            if [ ! -d "$domain" ]; then
              mkdir $domain
            fi
            file_name=$(echo $base | sed 's/@/_/g')_emails.txt
            if ls $file_name 1> /dev/null 2>&1; then
              mv $file_name $domain/
            fi
          done

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated emails"
          git push origin main
