name: Update Emails

on:
  push:
    branches:
      - main

jobs:
  update-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install faker pyyaml

      - name: Generate Emails
        run: |
          python script.py

      - name: Create Folders and Move Files
        run: |
          python -c "
import yaml
import os

with open('config.yaml', 'r') as f:
    config = yaml.safe_load(f)

bases = [
    config['gmail_base'],
    config['outlook_base'],
    config['popular_domains']['yahoo_base'],
    config['popular_domains']['hotmail_base'],
    config['popular_domains']['aol_base'],
    config['popular_domains']['icloud_base'],
    config['popular_domains']['proton_base'],
    config['popular_domains']['gmx_base']
]

for base in bases:
    domain = base.split('@')[1].split('.')[0]
    if not os.path.exists(domain):
        os.makedirs(domain)
    file_name = f'{base.replace('@', '_')}_emails.txt'
    if os.path.exists(f'{domain}/{file_name}'):
        counter = 1
        while os.path.exists(f'{domain}/{base.replace('@', '_')}_emails_{counter}.txt'):
            counter += 1
        file_name = f'{base.replace('@', '_')}_emails_{counter}.txt'
    if os.path.exists(file_name):
        os.rename(file_name, f'{domain}/{file_name}')
"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated emails"
          git push origin main
