name: Update Emails

on:
  push:
    branches:
      - main

jobs:
  update-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install faker pyyaml

      - name: Generate Emails
        run: |
          python script.py

      - name: Create Folders and Move Files
        run: |
          bases=$(python -c "
import yaml

with open('config.yaml', 'r') as f:
    config = yaml.safe_load(f)
    
bases = [
    config['gmail_base'],
    config['outlook_base'],
    config['popular_domains']['yahoo_base'],
    config['popular_domains']['hotmail_base'],
    config['popular_domains']['aol_base'],
    config['popular_domains']['icloud_base'],
    config['popular_domains']['proton_base'],
    config['popular_domains']['gmx_base']
]

for base in bases:
    print(base)
          ")
          for base in ${bases[@]}; do
            domain=$(echo $base | cut -d '@' -f 2 | cut -d '.' -f 1)
            if [ ! -d "$domain" ]; then
              mkdir $domain
            fi
            file_name=$(echo $base | sed 's/@/_/g')_emails.txt
            if [ -f "$domain/$file_name" ]; then
              counter=1
              while [ -f "$domain/$(echo $base | sed 's/@/_/g')_emails_$counter.txt" ]; do
                counter=$((counter + 1))
              done
              file_name=$(echo $base | sed 's/@/_/g')_emails_$counter.txt
            fi
            if ls $file_name 1> /dev/null 2>&1; then
              mv $file_name $domain/
            fi
          done

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated emails"
          git push origin main
